---
title: "Setting Up Supervised Learning Probems"
description: | 
author:
  - name: Kris Sankaran
    url: https://krisrs1128.github.com/LSLab
    affiliation: UW Madison
    affiliation_url: https://stat.wisc.edu
output:
  distill::distill_article:
    self_contained: false
---

1. We are making predictions all the time, often without realizing it. For
example, imagine we are waiting at a bus stop and want to guess how long it will
be before a bus arrives. We can combine many sources of evidence,
    * How many people are currently at the stop? If there are more people, we think
    a bus might arrive soon.
    * What time of day is it? If it's during rush hour, we would expect more
    frequent service.
    * What is the weather like? If it is poor weather, we might expect delays.
    * etc.
    
    To think about the process formally, we could imagine a vector $x_i \in \mathbb{R}^{D}$ reflecting $D$ characteristics of our environment. 
If we collected data about how long we actually had to wait, call it $y_i$, for
every day in a year, then we would have a dataset
\begin{align*}
\left(x_1, y_1\right) \\
\left(x_2, y_2\right) \\
\vdots \\
\left(x_{365}, y_{365}\right) \\
\end{align*}
  and we could try to summarize the relationship $x_i \to y_i$. Methods for making
this process automatic, based simply on a training dataset, are called
supervised learning methods.

2. In the above example, the inputs were a mix of counts (number of people at
stop?) and categorical (weather) data types, and our response was a nonnegative
continuous value. In general, we could have arbitrary data types for either
input or response variable. A few types of outputs are so common that they come
with their own names,
    * $y_i$ continuous $\to$ regression
    * $y_i$ categorical $\to$ classification
    
    For example, trying to determine whether a patient's disease will be cured by a
treatment is a classification problem -- the outcomes are either yes, they will
be cured, or no, they won't. Trying to estimate the crop yield of a plot of
farmland based on a satellite image is a regression problem -- it could be any
continuous, nonnegative number. There are in fact many other types of responses
(ordinal, multiresponse, survival, functional, image-to-image, ...) each which
come with their own names and set of methods, but for our purposes, it's enough
to focus on regression and classification.

3. There is a nice geometric way of thinking about supervised learning. For
regression, think of the inputs on the $x$-axis and the response on the
$y$-axis. Regression then becomes the problem of estimating a one-dimensional
curve from data.

    In higher-dimensions, this becomes a surface.
    
    If some of the inputs are categorical (e.g., poor vs. good weather), then the
regression function is no longer a continuous curve, but we can still identify
group means.

4. Classification has a similar geometric interpretation, except instead of a
continuous response, we have categorical labels. We can associate classes with
colors. If we have only one input, classification is the problem of learning
which regions of the input are associated with certain colors.

    In higher-dimensions, the view is analogous. We just want to find boundaries
between regions with clearly distinct colors. For example, for disease
recurrence, blood pressure and resting heart rate might be enough to make a good
guess about whether a patient will have recurrence or not.

### Model Classes

5. Drawing curves and boundaries sounds simple, but is a surprisingly difficult
problem, especially when the number of potentially informative features $D$ is
large. It helps to have predefined types of curves (and boundaries) that we can
refer to and use to partially automate the process of supervised learning. We'll
call an example of these predefined curve types a "model class." In later notes,
we'll discuss how exactly to choose one member of each model class that fits a
dataset well. For now, let's just build some intuition about what each model
class looks like and how we might be able to fit it with data.

#### Linear Models

6. Maybe the simplest curve is a linear one,
\begin{align*}
f_{b}\left(x\right) = b_0 + b_1 x_1.
\end{align*}
Here, $b_0$ gives the $y$-intercept and $b_1$ gives the slope. When we have many input features, the equivalent formula is
\begin{align*}
f_{b}\left(x\right) = b_0 + b_1 x_1 + \dots + b_{D}x_{D} := b^{T}x,
\end{align*}
where I've used the dot-product from linear algebra to simplify notation (after having appended a 1). This kind of model is called a _linear regression model_.

7. How do we find a $b$ that fits the data well? We can try to optimize a "loss"
function. This measures the quality of the fitted line. For linear regression, a
good choice is squared error loss,

\begin{align*}
L\left(b\right) = \sum_{i = 1}^{N} \left(y_i - b^{T}x_{i}\right)^2.
\end{align*}

7. For classification, we can imagine drawing a linear boundary. For simplicity,
we'll assume we have only two classes, though a similar partition of the space
can be made for arbitrary numbers of classes.

To describe this, we need to define a direction $b$ perpendicular to the
boundary. We will say that whenever
\begin{align*}
f_{b}\left(x\right) = \frac{1}{1 + \text{exp}\left(x^{T}b\right)}
\end{align*}
is larger than 0.5, we're in the orange region, and whenever it's smaller than
0.5, we're in the purple region. This kind of model is called a _logistic regression model_.

8. We need a loss function for logistic regression too. In theory, we could
continue to use squared error loss, but we can do better by considering the fact
that the true response is only one of two values. To make things concrete, say
that $y_i = 1$ whenever it is an orange point, otherwise $y_i = 0$. We can use
binary cross-entropy loss,

\begin{align*}
\sum_{i = 1}^{N} y_i \log\left(f_{b}\left(x_i\right)\right) + \left(1 - y_i\right) \log\left(1 - f_{b}\left(x_i\right)\right)
\end{align*}

To understand this loss, let's plot one term as a function of
$f_{b}\left(x_i\right)$, both when $y_i$ is 1 and when it is 0.

(draw picture)

8. Let's fit a linear regression in code. Below, I'm loading a dataset on .....
Notice that the response variable is continuous,

9. Let's do the same thing for a logistic regression.

#### Sparse Linear Models

10. In many cases, we will have recorded many types of features -- coordinates
of $x_{i}$ -- that are not actually related to the response. A model that knows
to ignore certain of the features will do better than a model that tries to use
all of them. This is the main idea behind using sparsity in linear regression.
We again fit the model
\begin{align*}
f_{b}\left(x\right) = b_0 + b_1 x_1 + \dots + b_{D}x_{D} := b^{T}x,
\end{align*}
but we make the assumption that many of the $b_{d}$ are exactly 0. Graphically,
we imagine that the response does not change at all as we change some of the
inputs, all else held equal.

11. This is how we implement the approach in `sklearn`.

12. The same idea can be applied to logistic regression. In this case, having a
coefficient $b_d = 0$  means that the probabilities for different class labels
do not change at all as features $x_d$ is changed.

13. Here is an implementation in `sklearn`.

#### Tree-based Models

14. Tree-based models fit a different class of curves. To motivate them,
consider making a prediction for the bus time arrival problem using the
following diagram,

Notice that we can use the same logic to do either regression or classification.
For regression, we associate each "leaf" at the bottom of the tree with a
continuous prediction. For classification, we associate it with the probability
for different classes. It turns out that we can train these models using squared
error and cross-entropy losses as before, though the details are beyond the
scope of these notes.

15. It's not immediately obvious, but these rules are equivalent to drawing
curves that are piecewise constant over subsets of the input space. Let's
convince ourselves using some pictures. First, notice that a tree with a single
split is exactly a "curve" that takes on two values, depending on the split
point,

If we split the same variable deeper, it creates more steps,

What if we had two variables? Depending on the order, of the splits, we create
different axis-aligned partitions,

Q: What would be the diagram if I had switched $x_1$ and $x_2$ in the tree?

16. A very common variation on tree-based models computes a large ensemble of
trees and then combines their curves in some way. How exactly they are combined
is beyond the scope of these notes, but this is what random forests and gradient
boosted decision trees are doing in the background.

17. We can implement these models in `sklearn` using the following code.

### Relationships across classes

17. The diagram below summarizes the relationships across classes.

18. When should we use which of these approaches? Here are some relative
strengths and weaknesses.

|  | Strengths | Weaknesses |
|---|---|---|
| Linear / Logistic Regression | * Often to easy interpret<br>* No tuning parameters<br>* Very fast to train | * Unstable when many features to pick from<br>* Can only fit linear curves / boundaries (though, see featurization notes) |
| Sparse Linear / Logistic Regression | * Often easy to interpret<br>* Stable even when many features to pick from<br>* Very fast to train | * Can only fit linear curves / boundaries |
| Tree-based Classification / Regression | * Can fit nonlinear functions of inputs | * Can be slow to train<br>* Somewhat harder to interpret |

19. Here is a flow chart you can use to guide the choice of which model class to
use when.

For example, try matching models to responses in the examples below,
* Q1: We want to predict whether a patient has a disease given just the genetic
profile. There are 1000 genes that can serve as predictors. There are only two
possible responses.
* Q2: A user on a site has been watching (too many...) episodes of Doctor
Who. How many more minutes will they remain on the site today? As predictors,
you have their features of their current and past viewing behavior (e.g.,
current time of day, number of hours per week for each of the last 4 weeks,
etc.). We suspect that there are important nonlinear relationships between
these predictors and the response.
* Q3: We are trying to predict the next hour's total energy production in a wind
farm. We have a years worth of past production and weather data, but right now,
we just want a baseline using current wind speed and the last hour's production.

The answers are,
* A1: Sparse logistic regression. We have two classes, and most of the genes are unlikely to be relevant for classification.
* A2: A tree-based method, like random forests or gradient boosting. This is because we anticipate a nonlinear relationship.
* A3: Linear regression. The response is continuous and we just need a baseline
using two predictors.